### ISSUE TITLE
Lic not exposed in metadata in 0.3.0

### ISSUE THREAD

**Issue by nazq** [AzureAD/microsoft-authentication-extensions-for-python#101]
Looks like the License info is not correctly exposed here.

[lic for lic in list(pkg_resources.require('msal')[0].get_metadata_lines('METADATA')) if lic.startswith('License')]
> ['License: MIT', 'License-File: LICENSE']

[lic for lic in list(pkg_resources.require('msal-extensions')[0].get_metadata_lines('METADATA')) if lic.startswith('License')]
> ['License: UNKNOWN']

Thanks

**Comment by rayluo** [comment]
Hi @nazq , were you trying to pack those libraries somehow and encountered some errors? The `msal` and `msal-extensions` both contain their license file, organized in same way.

Can you elaborate on how to reproduce this error? Or even better, you can try to hack your way and propose a PR for this.
