### ISSUE TITLE
Make `portalocker` dependency optional

### ISSUE THREAD

**Issue by jiasli** [AzureAD/microsoft-authentication-extensions-for-python#116]
`portalocker` relies on `PyWin32` which is not allowed on SPython and SAW.

In order to achieve https://github.com/Azure/azure-cli/issues/23315, `msal-extensions` should make the `portalocker` dependency optional to support SPython and SAW:

https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/69eef72b0e7a540ae00abb6a65e749cfce4d532a/msal_extensions/cache_lock.py#L9

See https://microsoft.sharepoint.com/sites/knowledgecenter/SitePages/SPython.aspx?ls=Ans_Office

**Comment by rayluo** [comment]
Roger that. Let's keep track in #96
