### ISSUE TITLE
distutils was removed in Python 3.12

### ISSUE THREAD

**Issue by edgarrmondragon** [AzureAD/microsoft-authentication-extensions-for-python#121]
See https://peps.python.org/pep-0632/

This is blocking applications that depend on [`azure-identity`](https://pypi.org/project/azure-identity/) to upgrade to Python 3.12.

**Comment by mickare** [comment]
Hey!
Please accept my apologies, but since there hasn't been any response or progress on this topic I'll now start to make some noise in the upstream `azure-identity` library. It has been known since a year (#118). I'm sorry about that.
