### ISSUE TITLE
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12

### ISSUE THREAD

**Issue by fredrike** [AzureAD/microsoft-authentication-extensions-for-python#123]
I get the following warning in pytest:

```
venv/lib/python3.10/site-packages/msal_extensions/cache_lock.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
````

**Comment by fredrike** [comment]
Well, I'm using the latest version fråm pypi, I do not have an extra environment to help you with testing.

**Comment by rayluo** [comment]
You do not have to use an extra environment. Your existing environment can pull the not-yet-released version from this official repo by:

    pip uninstall msal-extensions
    pip install git+https://github.com/AzureAD/microsoft-authentication-extensions-for-python.git@dev

Afterwards, you can always revert back to the existing 1.0.0 version by a normal `pip install msal-extensions`.
