### ISSUE TITLE
test: create a test plan for creds sharing work

### ISSUE THREAD

**Issue by yugangw-msft** [AzureAD/microsoft-authentication-extensions-for-python#13]
Based on the spec, let use create the test plan regarding how the creds sharing standard behavior would look like:
1. When a new account is added (login)
2. When an existing account is removed (logout)
3. When the creds is corrupted/missing.
4. (other scenarios)

**Comment by marstr** [comment]
We have an internal document hosted in our Teams chat that has a test-plan detailed for MSAL integration into the Azure CLI. Instead of copying this issue over into the https://github.com/Azure/azure-cli repository, seeing as the work is done I'll just close this issue.
