### ISSUE TITLE
Shall we expose configurable key in KeychainPersistence on OSX?

### ISSUE THREAD

**Issue by mattmshell** [AzureAD/microsoft-authentication-extensions-for-python#130]
`build_encrypted_persistence` doesn't provide sufficient control over the key name which leads to confusion. The value 'msal-extensions' is hardcoded in `KeychainPersistence`:

<img width="825" alt="image" src="https://github.com/AzureAD/microsoft-authentication-extensions-for-python/assets/103135056/838e4899-e43d-42ea-baaf-6a12022ed149">

**Comment by rayluo** [comment]
The `build_encrypted_persistence()` was meant to be a cross-platform helper so it contains no platform-specific parameters. Besides, the value "msal-extensions" was just a default value; it is customizable. You could copy `build_encrypted_persistence()`'s implementation and change the way it initializes `KeychainPersistence`.
