### ISSUE TITLE
Create a GNOME Keyring Token Cache (Linux only)

### ISSUE THREAD

**Issue by marstr** [AzureAD/microsoft-authentication-extensions-for-python#4]
Linux has a few solutions for protecting secrets. For people using the Desktop Environment(DE) [GNOME](https://www.gnome.org), [GNOME  Keyring](https://wiki.gnome.org/Projects/GnomeKeyring) is the natural choice. While it is not as ubiquitous as DP API for Windows users or KeyChain for MacOS users, it is a good way to get fairly significant coverage of Linux developers.

Just like #1 and #3, we should implement a class to facilitate interactions with GNOME Keyring that extends [SerializableTokenCache](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/f76f3c37c6bf7747971947d300f0a50d3ec701f7/msal/token_cache.py#L204). However, unlike those platforms, as of time of writing there is no .NET support for this secret backend.

Researching a little this afternoon, it seems like it is not unprecedented for folks who are not using GNOME as their DE to take a dependency on just this package. This may prove useful for us when running in containers, or other Linux environments that have no DE whatsoever. Experimentally, I was able to install `gnome-keyring` with only standard repositories in both an ubuntu:disco and centos7 container.

**Comment by marstr** [comment]
Doing more research on this today, and here's what I've found:

The [.NET implementation](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/c3c9d6ebb2e1467c336e600a5b074f2857bcd46a/src/Shared/Libsecret.cs) uses [libsecret](https://wiki.gnome.org/Projects/Libsecret), not [GNOME-keyring](https://wiki.gnome.org/Projects/GnomeKeyring) directly. This was a good choice, because libsecret is widely available and is more generic than just targeting GNOME-keyring.

## Sample of libsecret availability

| OS | Package |
| :---: | :----------- |
| Debian | https://packages.debian.org/search?keywords=libsecret |
| Ubuntu | https://packages.ubuntu.com/xenial/libsecret-1-0 |
| CentOS | https://centos.pkgs.org/7/centos-x86_64/libsecret-0.18.6-1.el7.x86_64.rpm.html |
| FreeBSD | https://www.freshports.org/security/libsecret | 

## Python Bindings

There also seem to be Python bindings already ready written, which should speed up life somewhat:


| Resource | Link |
| :----: | :----------|
| PyPI | https://pypi.org/project/PyGObject/ |
| PyGObject Secret Docs | https://lazka.github.io/pgi-docs/#Secret-1 |

**Comment by rayluo** [comment]
Some more materials that could be useful when we pick up this task (soon):

* [Python example: Lookup a password](https://developer.gnome.org/libsecret/unstable/py-lookup-example.html)
* [Potentiall issue](https://stackoverflow.com/questions/33575868/using-libsecret-i-cant-get-to-the-label-of-an-unlocked-item)
