### ISSUE TITLE
Cache resiliency improvements

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-extensions-for-python#61]
Cache lock improvements for Unix locking scenarios under stress as implemented by MSAL extensions for java [here](https://github.com/AzureAD/microsoft-authentication-extensions-for-java/pull/19)

**Comment by rayluo** [comment]
Not only we finished #63, we also implemented #100 based on the recent findings from Az CLI. Closing this issue now.
