### ISSUE TITLE
Create Token Provider Chain

### ISSUE THREAD

**Issue by marstr** [AzureAD/microsoft-authentication-extensions-for-python#7]
If there are multiple ambient tokens present in the system, there should be a prioritized list of where to find them and which to choose.

The semantics of this fit well with the decorator/proxy pattern in general, and is how @devigned is implementing this in the .NET extensions repository here:

https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/pull/13

**Comment by rayluo** [comment]
Closing old PR/issues. The "token provider chain" concept has since been implemented in Azure SDK's Azure Identity package. The MSAL EX package here specialized to become a lower-level building block that focuses on data encryption and cross-process locking.
