### ISSUE TITLE
Create Service Principal Token Provider

### ISSUE THREAD

**Issue by marstr** [AzureAD/microsoft-authentication-extensions-for-python#8]
Some folks will continue to authenticate using Service Principals (SPs). If there are available SP credentials via popular environment variables (i.e. `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET`), or if the MSAL Cache is extended to hold these credentials (see https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/14), there should be a token provider to retrieve them.

**Comment by rayluo** [comment]
Closing old PR/issues. The "token provider chain" concept has since been implemented in Azure SDK's Azure Identity package. The MSAL EX package here specialized to become a lower-level building block that focuses on data encryption and cross-process locking.
