### ISSUE TITLE
WindowsError: exception: access violation when using _MEMCPY

### ISSUE THREAD

**Issue by inatuwe** [AzureAD/microsoft-authentication-extensions-for-python#85]
I get an access violation when using the following methods:

  File "site-packages\msal\application.py", line 1168, in acquire_token_by_device_flow
  File "site-packages\msal\oauth2cli\oauth2.py", line 384, in obtain_token_by_device_flow
  File "site-packages\msal\oauth2cli\oauth2.py", line 347, in _obtain_token_by_device_flow
  File "site-packages\msal\oauth2cli\oidc.py", line 102, in _obtain_token
  File "site-packages\msal\oauth2cli\oauth2.py", line 765, in _obtain_token
  File "site-packages\msal\application.py", line 308, in <lambda>
  File "site-packages\msal\token_cache.py", line 297, in add
  File "site-packages\msal\token_cache.py", line 113, in add
  File "site-packages\msal\token_cache.py", line 176, in __add
  File "site-packages\msal_extensions\token_cache.py", line 49, in modify
  File "site-packages\msal_extensions\persistence.py", line 163, in save
  File "site-packages\msal_extensions\windows.py", line 80, in protect
  File "site-packages\msal_extensions\windows.py", line 39, in raw
WindowsError: exception: access violation writing 0x0000028F4B081000

I use the device flow and it properly redirects me to the browser, I enter the credentials, everything works fine, but when returning to the Windows application written in python, I receive the error.

Edit: The Windows version doesn't affect this issue:
~~Note: This error does not occur on Windows 10 Version 2004 (May 2020 Update), 19041, but is present with the newer Windows 10 Version 20H2 (October 2020 Update), 19042.~~

I have been able to fix the issue ~~for both Windows Versions~~ by adding the following line in windows.py (0.3.0):
Line 8 (directly after: "_MEMCPY = ctypes.cdll.msvcrt.memcpy")
_MEMCPY.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]

**Comment by rayluo** [comment]
Interesting. Can you share more information that you found in your research to reach the current solution? And, why was it working before without that line?

**Comment by inatuwe** [comment]
The idea came from here:
https://www.javaer101.com/en/article/18486797.html

To be honest, I don't understand the solution fully which is presented in the above link, but what caught my attention was that in the answer these argtypes are set. So I just tried it out.

On https://docs.python.org/3/library/ctypes.html in the section "Foreign functions", there it says:
"When a foreign function is called, each actual argument is passed to the from_param() class method of the items in the argtypes tuple, this method allows adapting the actual argument to an object that the foreign function accepts."

On the other hand I have now digged into it a bit further and tried to come up with a minimal working example, which revealed further side conditions...

One of the things I interpreted completely wrongly, was the dependency on the Windows version... There is none.

The constraints to reproduce the problem are:
- The product is bundled with PyInstaller
- I'm unfortunately still on Python 2.7 with the released version of our product... (sorry for that).

So, now the minimum working example: The attached zip file [data_blob_test.zip](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/files/6215516/data_blob_test.zip) contains the file data_blob_test.py.
This file contains the same DataBlob definition as in the msal_extensions source code (windows.py). Now the example works in almost all situations, but not in one.

I test now with different python versions and the two options of either executing the python script directly, or bundling it with PyInstaller and then executing it. The batch files used to create the executables with PyInstaller are also attached.

|Test run | Python version | Test object | Result |
|---------| ------------- |-------------| -----|
|1| Python 2.7.17 64-bit | Python script | Ok |
|2| Python 2.7.17 64-bit | PyInstaller Executable | Not Ok |
|3| Python 3.7.4 32-bit | Python script | Ok |
|4| Python 3.7.4 32-bit | PyInstaller Executable | Ok |
|5| Python 3.7.4 64-bit | Python script | Ok |
|6| Python 3.7.4 64-bit | PyInstaller Executable | Ok |

Command line outputs:

###Test run 1
C:\User\test>C:\User\Python27\python.exe data_blob_test.py
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]
This is the message.

###Test run 2
C:\User\test\data_blob_test_python_27-64>data_blob_test.exe
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]
Traceback (most recent call last):
  File "test\data_blob_test.py", line 40, in <module>
  File "test\data_blob_test.py", line 32, in raw
WindowsError: exception: access violation reading 0x0000042CAC36BFC4
[5968] Failed to execute script data_blob_test

###Test run 3
C:\User\test>C:\User\Python37-32\python.exe data_blob_test.py
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
b'This is the message.'

###Test run 4
C:\User\test\data_blob_test_python_37-32>data_blob_test.exe
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
b'This is the message.'

###Test run 5
C:\User\test>C:\User\Python37-64\python.exe data_blob_test.py
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
b'This is the message.'

###Test run 6
C:\User\test\data_blob_test_python_37-64>data_blob_test.exe
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
b'This is the message.'

Now, if I modify the python script by adding the line ...
_MEMCPY.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
 ... even the Python27-64 works!

C:\User\test\data_blob_test_python_27-64>data_blob_test.exe
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]
This is the message.

Now the solution works for me, besides that, I'm for sure planning to migrate to Python3 as quick as possible. Nevertheless, the fix doesn't seem to harm any other environment, so maybe we could consider to add it anyways?

**Comment by rayluo** [comment]
Thanks for your investigation! We will take a close look next week. A quick comment, for now: as you pointed out, the windows version is irrelevant; and now your test result indicates it is relative to pyinstaller. I'd assume you use PyInstaller 3.6 on your Python 2.7 (because this is [their last version still supporting Python 2.7](https://github.com/pyinstaller/pyinstaller/releases)), and you use a higher version (4.2?) of PyInstaller on your Python 3 environment. For the sake of cross-checking, would you mind also running PyInstaller 3.6 in your Python 3 environment to see whether it would also reproduce the error?

**Comment by inatuwe** [comment]
That's actually a good point, yes. So that makes now the following table:

|Test run | Python Version | PyInstaller Version | Result|
|----------|-----------------|----------------------|--------|
|1| Python: 2.7.17 64-bit| PyInstaller: 3.5 | Not Ok  |
|2| Python: 3.7.4 64-bit| PyInstaller: 4.2 | Ok |
|3| Python: 3.7.4 64-bit| PyInstaller: 3.5 | Ok |

As you see from the list, I'm not using the latest version of PyInstaller on Python 2.7.17. I tried to upgrade, but the command "pip install --upgrade pyinstaller" failed. It also failed on a fresh install of Python 2.7.18. I decided for now not to go down that rabbit whole... ;-). But the result suggests that it's probably not different from PyInstaller 3.5 to PyInstaller 3.6.

### Test run 3

Relevant lines from PyInstaller call:
90 INFO: PyInstaller: 3.5
91 INFO: Python: 3.7.4
92 INFO: Platform: Windows-10-10.0.19041-SP0

Result from Exe:
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
b'This is the message.'
