### ISSUE TITLE
Create MSI Token Provider

### ISSUE THREAD

**Issue by marstr** [AzureAD/microsoft-authentication-extensions-for-python#9]
Managed Service Identity is a mechanism for establishing identity based on the infrastructure that an application is being run on. The off-shoot is that if we are inspecting the inspecting for ambient credentials (as in #7,) we should absolutely include looking for MSI as a token provider.

**Comment by rayluo** [comment]
Closing old PR/issues. The "token provider chain" concept has since been implemented in Azure SDK's Azure Identity package. The MSAL EX package here specialized to become a lower-level building block that focuses on data encryption and cross-process locking.
